@startuml 持久化模块接口

' 
interface "Hold" {
    + load(id: List<String>, name: String) : data: Bytes
    + save(id: List<String>, name: String, data: Bytes) : void
    + remove(id: List<String>, name: String) : void
    + exists(id: List<String>, name: String) : bool
}
